# Run with cmake -P from the archive's staging directory: copies the files under each of DIRS (joined with |)
# into TOP/, later directories replacing earlier ones, skips paths matching EXCLUDE, and zips TOP into OUTPUT.
string(REPLACE "|" ";" DIRS "${DIRS}")
string(REPLACE "|" ";" EXCLUDE "${EXCLUDE}")

file(REMOVE_RECURSE ${TOP})
foreach(DIR ${DIRS})
	if(NOT IS_DIRECTORY ${DIR})
		continue()
	endif()
	file(GLOB_RECURSE FILES RELATIVE ${DIR} ${DIR}/*)
	foreach(FILE ${FILES})
		set(SKIP FALSE)
		foreach(PATTERN ${EXCLUDE})
			if("/${FILE}" MATCHES "${PATTERN}")
				set(SKIP TRUE)
			endif()
		endforeach()
		if(NOT SKIP)
			get_filename_component(PARENT ${TOP}/${FILE} DIRECTORY)
			file(MAKE_DIRECTORY ${PARENT})
			file(COPY_FILE ${DIR}/${FILE} ${TOP}/${FILE})
		endif()
	endforeach()
endforeach()

file(MAKE_DIRECTORY ${TOP})
file(ARCHIVE_CREATE OUTPUT ${OUTPUT} PATHS ${TOP} FORMAT zip)
